version: '3'

services:
  core:
    container_name: squirrel-core
    build: .
    restart: always
    links:
      - ms
      - db
      - redis
    ports:
      - ${CORE_PORT:-8000}:8000
    volumes:
      - data.squirrel:/data
      - ./squirrel_core:/app/squirrel_core
    tty: true

  ms:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=/data.ms
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - data.ms:/data.ms
    restart: unless-stopped
    env_file:
      - core.env

  db:
    container_name: postgres
    image: postgres:alpine
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - data.db:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - core.env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - data.redis:/data
    restart: unless-stopped
    env_file:
      - core.env

volumes:
  data.ms:
  data.db:
  data.redis:
  data.squirrel: